[package]
name = "mars-core"
version = "1.0.0"
authors = ["Spike Spiegel <spikeonmars@protonmail.com>"]
edition = "2018"
description = "Mars is a fully automated, on-chain credit protocol built on Terra and governed by a decentralised community of users and developers"
license = "GPL-3.0"
repository = "https://github.com/mars-protocol/mars-core"
homepage = "https://marsprotocol.io"
documentation = "https://docs.marsprotocol.io/mars-protocol/developers/protocol-overview"
readme = "README.md"
keywords = ["terra", "cosmwasm"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
terra-cosmwasm = "2.2.0"

cw2 = "0.9.0"
cw20 = "0.9.0"
cw20-base = { version = "0.9.0", features = ["library"] }

cosmwasm-std = "0.16.2"

schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
thiserror = "1.0.23"

astroport = "1.0"

basset = { git = "https://github.com/lidofinance/lido-terra-contracts", tag = "v1.0.2" }

[profile.release]
overflow-checks = true
