on: push

name: Integration Tests

jobs:
  build-mars-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build artifacts
        run: |
          $GITHUB_WORKSPACE/scripts/build_artifacts.sh
      - name: upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: mars-artifacts
          path: |
            artifacts

  test:
    runs-on: ubuntu-latest
    needs: build-mars-artifacts
    strategy:
      matrix:
        tests: [
          { name: borrow_exact_liquidity, block-time: 250 },
          { name: dynamic_interest_rate_thresholds, block-time: 250 },
          { name: governance, block-time: 250 },
          { name: incentives, block-time: 250 },
          { name: liquidations, block-time: 250 },
          { name: ma_token_finalize_transfer, block-time: 250 },
          { name: ma_token_underlying_liquidity_amount, block-time: 250 },
          #{ name: migrating_through_council, block-time: 250 },
          { name: oracle_native, block-time: 1500 },
          { name: oracle_red_bank, block-time: 1500 },
          { name: oracle_spot_and_twap, block-time: 250 },
          { name: redbank_overflow_checks, block-time: 250 },
          { name: repay_ust, block-time: 250 },
          { name: rewards_distribution, block-time: 250 },
          { name: staking, block-time: 250 },
          { name: utilization_rate_updates, block-time: 250 },
          { name: vesting, block-time: 250 }
        ]
    env:
      CW_PLUS_ARTIFACTS_PATH: /home/runner/work/cw-plus-artifacts
      MARS_MOCKS_ARTIFACTS_PATH: /home/runner/work/mars-mocks-artifacts
      ASTROPORT_ARTIFACTS_PATH: /home/runner/work/astroport-artifacts
    steps:
      - uses: actions/checkout@v2
      - name: download cw-plus artifacts
        run: |
          mkdir $CW_PLUS_ARTIFACTS_PATH
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.9.1/cw1_whitelist.wasm -O $CW_PLUS_ARTIFACTS_PATH/cw1_whitelist.wasm
          wget https://github.com/CosmWasm/cw-plus/releases/download/v0.9.1/cw20_base.wasm -O $CW_PLUS_ARTIFACTS_PATH/cw20_base.wasm
      - name: download mars-mocks artifacts
        run: |
          mkdir $MARS_MOCKS_ARTIFACTS_PATH
          echo ${{ secrets.GITHUB_TOKEN }}
          wget --header 'Authorization: token ${{ secrets.GITHUB_TOKEN }}' https://github.com/mars-protocol/mars-mocks/releases/download/v1.0.0/cosmwasm-artifacts.tar.gz -O $MARS_MOCKS_ARTIFACTS_PATH/cosmwasm-artifacts.tar.gz
          cd $MARS_MOCKS_ARTIFACTS_PATH
          tar -xf cosmwasm-artifacts.tar.gz
          mv artifacts/* .
          rm -rf artifacts
          rm cosmwasm-artifacts.tar.gz
      - name: download astroport artifacts
        run: |
          mkdir $ASTROPORT_ARTIFACTS_PATH
          wget https://github.com/astroport-fi/astroport-core/releases/download/v1.0.0/cosmwasm-artifacts.tar.gz -O $ASTROPORT_ARTIFACTS_PATH/cosmwasm-artifacts.tar.gz
          cd $ASTROPORT_ARTIFACTS_PATH
          tar -xf cosmwasm-artifacts.tar.gz
          mv artifacts/* .
          rm -rf artifacts
          rm cosmwasm-artifacts.tar.gz
      - name: download mars artifacts
        uses: actions/download-artifact@v2
        with:
          name: mars-artifacts
          path: artifacts
      - name: npm install
        run: |
          cd $GITHUB_WORKSPACE/scripts
          npm install
          npm install -g typescript
          npm install -g ts-node
      - name: LocalTerra
        run: |
          cd
          git clone --depth 1 https://github.com/terra-money/LocalTerra.git
          sed -E -i '/timeout_(propose|prevote|precommit|commit)/s/[0-9]+m?s/${{ matrix.tests.block-time }}ms/' LocalTerra/config/config.toml
          docker-compose -f $HOME/LocalTerra/docker-compose.yml up -d
      - name: run test
        run: |
          cd $GITHUB_WORKSPACE/scripts
          ls -alh ../artifacts
          node --loader ts-node/esm tests/${{ matrix.tests.name }}.ts
      - name: stop LocalTerra
        run: docker-compose -f $HOME/LocalTerra/docker-compose.yml down
